#!/usr/bin/python3 -u

# Author: Russ Webber <russ.webber@greenroomrobotics.com>

import time
import hashlib
import sys
import os
import logging
import traceback
import urllib.parse
from urllib.parse import urlparse
from pathlib import Path
import subprocess

APT_CACHE_PATH = Path("/var/cache/apt")
GITLFS_APT_CACHE_PATH = APT_CACHE_PATH / "gitlfs"


class APTMessage(object):
    MESSAGE_CODES = {
        100: 'Capabilities',
        102: 'Status',
        200: 'URI Start',
        201: 'URI Done',
        400: 'URI Failure',
        600: 'URI Acquire',
        601: 'Configuration',
    }

    def __init__(self, code, headers):
        self.code = code
        self.headers = headers

    def encode(self):
        result = '{0} {1}\n'.format(self.code, self.MESSAGE_CODES[self.code])
        for item in list(self.headers.keys()):
            if self.headers[item] is not None:
                result += '{0}: {1}\n'.format(item, self.headers[item])
        return result + '\n'


class APTTransport:
    def __init__(self):
        self.__eof = False

    def read_message(self):
        """
        Apt uses for communication with its methods the text protocol similar
        to http. This function parses the protocol messages from stdin.
        """
        if self.__eof:
            return None
        result = {}
        line = sys.stdin.readline()
        while line == '\n':
            line = sys.stdin.readline()
        if not line:
            self.__eof = True
            return None
        s = line.split(" ", 1)
        result['_number'] = int(s[0])
        result['_text'] = s[1].strip()

        while not self.__eof:
            line = sys.stdin.readline()
            if not line:
                self.__eof = True
                return result
            if line == '\n':
                return result
            (item, value) = line.split(":", 1)
            if not result.get(item):
                result[item] = []
            result[item].append(value.strip())
        return result

    def send(self, code, headers):
        message = APTMessage(code, headers)
        sys.stdout.write(message.encode())

    def send_capabilities(self):
        self.send(100, {
            'Version': '1.1',
            'Single-Instance': 'true',
            'Send-Config': 'true'})

    def send_status(self, headers):
        self.send(102, headers)

    def send_uri_start(self, headers):
        self.send(200, headers)

    def send_uri_done(self, headers):
        self.send(201, headers)

    def send_uri_failure(self, headers):
        self.send(400, headers)


class GitLFSRepo:
    @staticmethod
    def Clone(git_uri: str):
        GITLFS_APT_CACHE_PATH.mkdir(exist_ok=True)

        repo_name = ''
        proc = subprocess.run(['git', 'clone', git_uri, repo_name], cwd=GITLFS_APT_CACHE_PATH, capture_output=True)

        if proc.returncode == 0:
            return GitLFSRepo(Path(repo_name))
        else:
            raise RuntimeError(f"Failed to git-clone: {proc.stderr}")

    def __init__(self, path: Path):
        self.repo_root_path = path

        if not (path / ".git").exists():
            raise RuntimeError("Given path is not a git repository")

        if not (path / ".git"/ "lfs").exists():
            self.lfs_init()

    def git_reset_hard(self):
        subprocess.run(['git', 'reset', '--hard'], cwd=self.repo_root_path, capture_output=True)

    def git_pull(self):
        p = subprocess.run(['git', 'pull'], cwd=self.repo_root_path, capture_output=True)
        if p.returncode != 0:
            raise RuntimeError(f"Failed to git-pull: {p.stderr}")

    def lfs_init(self):
        p = subprocess.run(['git', 'lfs', 'install'], cwd=self.repo_root_path, capture_output=True)
        if p.returncode != 0:
            raise RuntimeError(f"Failed to git-lfs-install: {p.stderr}")

    def lfs_fetch_path(self, filename: Path):
        p = subprocess.run(['git', 'lfs', 'fetch', '-I', str(filename)], cwd=self.repo_root_path, capture_output=True)
        if p.returncode != 0:
            raise RuntimeError(f"Failed to git-lfs-fetch: {p.stderr}")

    # def lfs_checkout_path(self, file_path: Path):
    #     "git lfs checkout PATH"
        # this might not be needed - can just pass the object filename
        # pass

    def resolve_path(self, filename: str):
        return Path.cwd()


class GitLFSMethod:
    def __init__(self, config_file='/etc/apt/gitlfs.conf'):
        self.transport = APTTransport()
        self.transport.send_capabilities()
        self.repos = {}

    def fail(self, uri, message='Failed'):
        self.transport.send_uri_failure({'URI': uri, 'Message': message})

    def run(self):
        """Loop through requests on stdin"""
        while True:
            message = self.transport.read_message()
            if message is None:
                return 0
            if message['_number'] == 601:
                try:
                    self.configure(message)
                except Exception as e:
                    logging.error(traceback.format_exc())
                    self.fail(message['URI'][0], e.__class__.__name__ + ": " + str(e))
            elif message['_number'] == 600:
                try:
                    self.fetch(message)
                except Exception as e:
                    logging.error(traceback.format_exc())
                    self.fail(message['URI'][0], e.__class__.__name__ + ": " + str(e))
            else:
                self.fail(message['URI'][0], str(message['_text']))

    def configure(self, message):
        """
        Reads APT configuration (dict) and checks for proxy settings by reading
        all available options with in 'Config-Item' and lookinup
        'Acquire::http::Proxy'
        """
        for item in message['Config-Item']:
            if item.startswith('Acquire::http::Proxy'):
                (key, value) = item.split('=', 1)
                if key == 'Acquire::http::Proxy':
                    os.environ['http_proxy'] = value
                    os.environ['https_proxy'] = value

    @staticmethod
    def uri_to_git(uri: urllib.parse.ParseResult):

        out = ""

        if uri.scheme == 'gitlfs+https':
            # https://github.com/Greenroom-Robotics/packages-test.git
            # Out[9]: ParseResult(scheme='gitlfs+https', netloc='github.com', path='/Greenroom-Robotics/packages-test.git/Release', params='', query='', fragment='')
            out += "https://"
        elif uri.scheme == "gitlfs+git":
            # In [11]: urlparse("gitlfs+git://git@github.com:Greenroom-Robotics/packages-test.git")
            # Out[11]: ParseResult(scheme='gitlfs+git', netloc='git@github.com:Greenroom-Robotics', path='/packages-test.git', params='', query='', fragment='')
            out += "git@"
            # TODO

        out += uri.netloc
        paths = Path(uri.path)
        

        return out

    def fetch(self, msg):
        logging.debug(msg)
        uri = urlparse(msg['URI'][0])
        output_filename = msg['Filename'][0]
        # self.transport.send_status({'URI': self.uri, 'Message': 'Waiting for headers'})

        git_uri = self.uri_to_git(uri)
        repo = self.repos.get(git_uri, None)

        if repo is None:
            # haven't seen this uri this session, so we should refresh or clone it
            self.transport.send_status({'URI': msg['URI'][0], 'Message': 'Waiting for headers'})
            if True: # if in cache
                repo = GitLFSRepo(git_uri)
                repo.git_reset_hard()
                repo.git_pull()
            else:
                repo = GitLFSRepo.Clone(uri.netloc, uri)

            self.repos[uri] = repo

        file_path = repo.resolve_path(filename)

        if True:
            self.transport.send_status({
                'URI': msg['URI'][0],
                'Message': 'Waiting for headers'})
            repo.lfs_fetch_path(filename)

        if not file_path.is_file() or not file_path.exists():
            error_detail = "Filename is not in git repository"
            self.transport.send_uri_failure({
                'URI': msg['URI'][0],
                'Message': f'{error_detail}',
                'FailReason': 'HttpError404'})
            return

        file_size = 0

        self.transport.send_uri_start({
            'URI': msg['URI'][0],
            'Size': file_size,
            'Last-Modified': response.headers.get('last-modified')})

        hash_sha256 = hashlib.sha256()
        hash_sha512 = hashlib.sha512()
        hash_md5 = hashlib.md5()

        # hash_sha512.

        # hash_sha256.update(data)
        # hash_sha512.update(data)
        # hash_md5.update(data)

        self.transport.send_uri_done({
            'URI': msg['URI'][0],
            'Filename': output_filename,
            'Size': file_size,
            'Last-Modified': response.headers.get('last-modified'),
            'MD5-Hash': hash_md5.hexdigest(),
            'MD5Sum-Hash': hash_md5.hexdigest(),
            'SHA256-Hash': hash_sha256.hexdigest(),
            'SHA512-Hash': hash_sha512.hexdigest()})


if __name__ == '__main__':
    try:
        config = '/etc/apt/gitlfs.conf'
        if len(sys.argv) == 2 and os.path.isfile(sys.argv[1]):
            config = sys.argv[1]
        method = GitLFSMethod(config)
        logging.getLogger().setLevel(logging.DEBUG)
        logging.debug(f"Working dir: {Path.cwd()}")
        logging.debug(f"UID: {subprocess.run(['/usr/bin/id'], capture_output=True).stdout.decode('utf8')}")

        ret = method.run()
        sys.exit(ret)
    except KeyboardInterrupt:
        pass
